typedef struct LIST_STRUCT LIST_TYPEDEF;

typedef struct NODE_STRUCT NODE_TYPEDEF;

void LIST_METHOD(init)  (LIST_TYPEDEF * l);

void LIST_METHOD(clear) (LIST_TYPEDEF * l);

void LIST_METHOD(erase) (NODE_TYPEDEF * node);

NODE_TYPEDEF * LIST_METHOD(push,back)  (LIST_TYPEDEF * l, VALUE_TYPEDEF value);

NODE_TYPEDEF * LIST_METHOD(push,front) (LIST_TYPEDEF * l, VALUE_TYPEDEF value);

NODE_TYPEDEF * LIST_METHOD(insert,before) (NODE_TYPEDEF * node, VALUE_TYPEDEF value);

NODE_TYPEDEF * LIST_METHOD(insert,after)  (NODE_TYPEDEF * node, VALUE_TYPEDEF value);

NODE_TYPEDEF * LIST_METHOD(first) (const LIST_TYPEDEF * l);

NODE_TYPEDEF * LIST_METHOD(last)  (const LIST_TYPEDEF * l);

NODE_TYPEDEF * LIST_METHOD(next)  (const NODE_TYPEDEF * l);

NODE_TYPEDEF * LIST_METHOD(prev)  (const NODE_TYPEDEF * l);
